version: "3"

services:
  db:
    container_name: freshdesk_db
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./.data:/var/lib/postgresql/datas
    networks:
      - freshdesk-db-net

  cache:
    container_name: freshdesk_cache
    image: redis:alpine
    restart: always
    networks:
      - freshdesk-db-net

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    container_name: Freshdesk
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - freshdesk-db-net

networks:
  freshdesk-db-net:
    driver: bridge
